logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: DEBUG
server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: 1234
#    url: jdbc:mariadb://127.0.0.1:3308/board #house
    url: jdbc:mariadb://127.0.0.1:3306/board #company
    username: root
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true